[project]
name = "NapCatQQ-Desktop"
version = "beta 1.1.0"
description = "为 NapCat 提供管理界面（GUI），目的是让用户能够更快速、更直观的使用 NapCat"
authors = [
    {name = "Qiao", email = "qiaohuayuquan@qq.com"},
]
dependencies = [
    "httpx>=0.27.2",
    "loguru>=0.7.2",
    "pydantic>=2.9.0",
    "PySide6-Fluent-Widgets>=1.6.3",
    "creart>=0.3.0",
    "psutil>=6.0.0",
    "markdown>=3.7",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "GPLv3"}


[tool.pdm]
distribution = false
