name: Beta_release

on:
  push:
    tags:
      - "beta*"
permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - uses: Nuitka/Nuitka-Action@main
      name: Build Windows Application
      with:
        script-name: main.py
        onefile: true
        enable-plugins: pyside6
        disable-console: true
        windows-icon-from-ico: src/Ui/resource/image/icon.ico

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          draft: true
          name: "NapCat-Desktop bata*"
          files: |
              build/*.exe
              build/*.bin
              build/*.app/**/*