name: Release

on:
  push:
    tags:
      - "v*"
permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyInstaller
        pip install -r requirements.txt
    - name: Build Windows Application
      run: |
           pyinstaller main.py -w -F
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        directory: './dist/main'
        exclusions: '*.git* /*node_modules/* .editorconfig'
