name: 构建发布

on:
  push:
    tags:
      - 'v*.*.*'  # 匹配版本标签
      - 'ci*'

permissions:
  contents: write

jobs:

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "检出代码"
        uses: actions/checkout@v2

      - name: "设置标签和 body 内容"
        id: get_info
        run: |
          TAG_NAME=$(echo "${GITHUB_REF#refs/tags/}")
          BODY=$(cat docs/CHANGELOG.md)
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "BODY<<EOF" >> $GITHUB_ENV
          echo "$BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: "创建发布草案"
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: "./NapCat-Desktop.exe"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG_NAME }}
          name: "NapCat Release ${{ env.TAG_NAME }}"
          body: ${{ env.BODY }}
