name: 调试编译

on:
    workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: "检出代码"
      uses: actions/checkout@v2

    - name: "设置 Python"
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: "安装依赖"
      run: pip install -r requirements.txt

    - uses: Nuitka/Nuitka-Action@main
      name: "构建 Windows 版本"
      with:
        script-name: main.py
        onefile: true
        enable-plugins: pyside6
        windows-icon-from-ico: src/Ui/resource/image/icon.ico
        output-filename: "NapCat-Desktop"

    - name: "启用开发者命令提示符"
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: "添加清单文件"
      run: |
        mt.exe -manifest ./assets/NapCat-Desktop.exe.manifest -outputresource:./build/NapCat-Desktop.exe;1

    - name: "上传工件"
      uses: actions/upload-artifact@v3
      with:
        name: NapCat-Desktop
        path: ./build/NapCat-Desktop.exe
