name: test_build

on:
  push:
    tags:
      - "test*"
permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: windows-latest # For Linux, use ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - uses: Nuitka/Nuitka-Action@main
      name: Build Windows Application
      with:
        script-name: main.py
        onefile: true
        enable-plugins: pyside6
        disable-console: false
        windows-icon-from-ico: src/Ui/resource/image/icon.ico
        output-filename: "NapCat-Desktop"

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Add Manifest
      run: |
            mt.exe -manifest ./assets/NapCat-Desktop.exe.manifest -outputresource:./build/NapCat-Desktop.exe;1
